// Realistic Pre-seeded Dataset for Attendance & Employee Management Application

export const INITIAL_COMPANY = {
  name: "AdTech Prime Infrastructure Ltd.",
  code: "ADTECH-INFRA",
  contractorName: "Javed Contractor",
  contractorMobile: "+91 98765 43210",
  contractorEmail: "admin@adtechprime.com",
};

export const INITIAL_PROJECTS = [
  {
    id: "proj-101",
    name: "Metro Station Terminal A",
    code: "METRO-A",
    locationName: "Connaught Place Sector 4, New Delhi",
    latitude: 28.6139,
    longitude: 77.2090,
    allowedRadiusMeters: 500,
    clientName: "Delhi Metro Rail Corp",
    status: "active",
  },
  {
    id: "proj-102",
    name: "Expressway Flyover Bypass B",
    code: "FLYOVER-B",
    locationName: "Ring Road Interchange, Gurugram",
    latitude: 28.4595,
    longitude: 77.0266,
    allowedRadiusMeters: 750,
    clientName: "National Highway Authority",
    status: "active",
  },
  {
    id: "proj-103",
    name: "City Prime Commercial Mall C",
    code: "MALL-C",
    locationName: "Cyber Hub Phase 3, Gurugram",
    latitude: 28.4950,
    longitude: 77.0890,
    allowedRadiusMeters: 400,
    clientName: "DLF Urban Developers",
    status: "active",
  },
];

export const INITIAL_GROUPS = [
  {
    id: "grp-201",
    name: "Electrical & Wiring Squad",
    description: "High-voltage cabling, panel installations, and site lighting.",
    leadEmployeeId: "emp-101",
  },
  {
    id: "grp-202",
    name: "Civil & Masonry Team",
    description: "Concrete casting, brickwork, and structural reinforcement.",
    leadEmployeeId: "emp-102",
  },
  {
    id: "grp-203",
    name: "HVAC & Ducting Crew",
    description: "Air conditioning ducts, ventilation, and chiller piping.",
    leadEmployeeId: "emp-104",
  },
];

export const INITIAL_EMPLOYEES = [
  {
    id: "emp-101",
    name: "Rajesh Kumar",
    employeeCode: "1024",
    companyCode: "ADTECH-INFRA",
    mobile: "+91 98112 34567",
    joiningDate: "2024-01-15",
    designation: "Senior Electrician",
    dailySalary: 950,
    salaryType: "daily",
    emergencyContact: "+91 98112 00001 (Wife)",
    assignedGroupId: "grp-201",
    assignedProjectId: "proj-101",
    status: "active",
    avatar: "https://images.unsplash.com/photo-1540569014015-19a7be504e3a?w=150&auto=format&fit=crop&q=80",
  },
  {
    id: "emp-102",
    name: "Sunil Verma",
    employeeCode: "1847",
    companyCode: "ADTECH-INFRA",
    mobile: "+91 98765 12345",
    joiningDate: "2024-02-01",
    designation: "Master Mason",
    dailySalary: 900,
    salaryType: "daily",
    emergencyContact: "+91 98765 99999 (Brother)",
    assignedGroupId: "grp-202",
    assignedProjectId: "proj-101",
    status: "active",
    avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80",
  },
  {
    id: "emp-103",
    name: "Amit Sharma",
    employeeCode: "5632",
    companyCode: "ADTECH-INFRA",
    mobile: "+91 98333 44455",
    joiningDate: "2024-03-10",
    designation: "Site Welder & Fitter",
    dailySalary: 850,
    salaryType: "daily",
    emergencyContact: "+91 98333 00000 (Father)",
    assignedGroupId: "grp-201",
    assignedProjectId: "proj-102",
    status: "active",
    avatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80",
  },
  {
    id: "emp-104",
    name: "Vikram Singh",
    employeeCode: "3091",
    companyCode: "ADTECH-INFRA",
    mobile: "+91 97111 22233",
    joiningDate: "2024-04-05",
    designation: "HVAC Technician",
    dailySalary: 880,
    salaryType: "daily",
    emergencyContact: "+91 97111 99999 (Wife)",
    assignedGroupId: "grp-203",
    assignedProjectId: "proj-103",
    status: "active",
    avatar: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150&auto=format&fit=crop&q=80",
  },
  {
    id: "emp-105",
    name: "Dinesh Yadav",
    employeeCode: "4412",
    companyCode: "ADTECH-INFRA",
    mobile: "+91 96543 88877",
    joiningDate: "2024-05-12",
    designation: "General Site Labour",
    dailySalary: 700,
    salaryType: "daily",
    emergencyContact: "+91 96543 00000 (Mother)",
    assignedGroupId: "grp-202",
    assignedProjectId: "proj-101",
    status: "active",
    avatar: "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=150&auto=format&fit=crop&q=80",
  },
];

export const INITIAL_ATTENDANCE = [
  // Today's records (2026-08-19)
  {
    id: "att-301",
    employeeId: "emp-101",
    date: "2026-08-19",
    punchInTime: "09:52 AM",
    punchOutTime: null, // Currently working, overtime candidate
    projectId: "proj-101",
    siteName: "Metro Station Terminal A",
    punchInLat: 28.6141,
    punchInLng: 77.2088,
    punchInAddress: "Metro Gate 2, Connaught Place, New Delhi",
    punchOutLat: null,
    punchOutLng: null,
    punchOutAddress: null,
    punchInSelfie: "https://images.unsplash.com/photo-1540569014015-19a7be504e3a?w=200&auto=format&fit=crop&q=80",
    punchOutSelfie: null,
    status: "present",
    workingHours: 8.5,
    regularHours: 8.0,
    halfDayHours: 0,
    overtimeHours: 2.5,
    overtimePeriod1: true, // 6:30 PM - 9:00 PM
    overtimePeriod2: false,
    overtimeStatus: "pending", // Waiting for Superadmin approval!
    payCancelled: false,
    payCancelReason: null,
  },
  {
    id: "att-302",
    employeeId: "emp-102",
    date: "2026-08-19",
    punchInTime: "09:58 AM",
    punchOutTime: "06:05 PM",
    projectId: "proj-101",
    siteName: "Metro Station Terminal A",
    punchInLat: 28.6139,
    punchInLng: 77.2090,
    punchInAddress: "Metro Gate 1, Connaught Place, New Delhi",
    punchOutLat: 28.6140,
    punchOutLng: 77.2091,
    punchOutAddress: "Metro Gate 1 Exit, New Delhi",
    punchInSelfie: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200&auto=format&fit=crop&q=80",
    punchOutSelfie: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200&auto=format&fit=crop&q=80",
    status: "present",
    workingHours: 8.1,
    regularHours: 8.0,
    halfDayHours: 0,
    overtimeHours: 0,
    overtimePeriod1: false,
    overtimePeriod2: false,
    overtimeStatus: "none",
    payCancelled: false,
    payCancelReason: null,
  },
  {
    id: "att-303",
    employeeId: "emp-103",
    date: "2026-08-19",
    punchInTime: "10:25 AM", // Late punch!
    punchOutTime: null,
    projectId: "proj-102",
    siteName: "Expressway Flyover Bypass B",
    punchInLat: 28.4590,
    punchInLng: 77.0260,
    punchInAddress: "Flyover Pillar 42, Ring Road, Gurugram",
    punchOutLat: null,
    punchOutLng: null,
    punchOutAddress: null,
    punchInSelfie: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=200&auto=format&fit=crop&q=80",
    punchOutSelfie: null,
    status: "late",
    workingHours: 7.5,
    regularHours: 7.5,
    halfDayHours: 0,
    overtimeHours: 0,
    overtimePeriod1: false,
    overtimePeriod2: false,
    overtimeStatus: "none",
    payCancelled: false,
    payCancelReason: null,
  },

  // Past day records (2026-08-18)
  {
    id: "att-304",
    employeeId: "emp-101",
    date: "2026-08-18",
    punchInTime: "09:50 AM",
    punchOutTime: "09:15 PM",
    projectId: "proj-101",
    siteName: "Metro Station Terminal A",
    punchInLat: 28.6139,
    punchInLng: 77.2090,
    punchInAddress: "Metro Gate 2, Connaught Place",
    punchOutLat: 28.6139,
    punchOutLng: 77.2090,
    punchOutAddress: "Metro Gate 2, Connaught Place",
    punchInSelfie: "https://images.unsplash.com/photo-1540569014015-19a7be504e3a?w=200&auto=format&fit=crop&q=80",
    punchOutSelfie: "https://images.unsplash.com/photo-1540569014015-19a7be504e3a?w=200&auto=format&fit=crop&q=80",
    status: "present",
    workingHours: 11.2,
    regularHours: 8.0,
    halfDayHours: 0,
    overtimeHours: 2.5,
    overtimePeriod1: true,
    overtimePeriod2: false,
    overtimeStatus: "approved", // Superadmin Approved
    payCancelled: false,
    payCancelReason: null,
  },
  {
    id: "att-305",
    employeeId: "emp-102",
    date: "2026-08-18",
    punchInTime: "10:00 AM",
    punchOutTime: "02:00 PM", // Half-day!
    projectId: "proj-101",
    siteName: "Metro Station Terminal A",
    punchInLat: 28.6139,
    punchInLng: 77.2090,
    punchInAddress: "Metro Station Terminal A",
    punchOutLat: 28.6139,
    punchOutLng: 77.2090,
    punchOutAddress: "Metro Station Terminal A",
    punchInSelfie: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200&auto=format&fit=crop&q=80",
    punchOutSelfie: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200&auto=format&fit=crop&q=80",
    status: "half_day",
    workingHours: 4.0,
    regularHours: 4.0,
    halfDayHours: 4.0,
    overtimeHours: 0,
    overtimePeriod1: false,
    overtimePeriod2: false,
    overtimeStatus: "none",
    payCancelled: false,
    payCancelReason: null,
  },
  {
    id: "att-306",
    employeeId: "emp-104",
    date: "2026-08-18",
    punchInTime: "09:55 AM",
    punchOutTime: "11:10 PM", // Full Late Night OT (Period 1 + Period 2)
    projectId: "proj-103",
    siteName: "City Prime Commercial Mall C",
    punchInLat: 28.4950,
    punchInLng: 77.0890,
    punchInAddress: "Cyber Hub Phase 3, Gurugram",
    punchOutLat: 28.4950,
    punchOutLng: 77.0890,
    punchOutAddress: "Cyber Hub Phase 3, Gurugram",
    punchInSelfie: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=200&auto=format&fit=crop&q=80",
    punchOutSelfie: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=200&auto=format&fit=crop&q=80",
    status: "present",
    workingHours: 13.2,
    regularHours: 8.0,
    halfDayHours: 0,
    overtimeHours: 4.5,
    overtimePeriod1: true,
    overtimePeriod2: true,
    overtimeStatus: "approved",
    payCancelled: false,
    payCancelReason: null,
  },
];

export const INITIAL_EXPENSES_ADVANCES = [
  {
    id: "ea-401",
    employeeId: "emp-101",
    projectId: "proj-101",
    amount: 1500,
    date: "2026-08-10",
    type: "advance",
    classification: "personal",
    purpose: "Medical emergency advance",
    description: "Advance cash paid to Rajesh for family doctor consultation.",
    receiptPhoto: null,
    status: "approved",
  },
  {
    id: "ea-402",
    employeeId: "emp-102",
    projectId: "proj-101",
    amount: 850,
    date: "2026-08-15",
    type: "expense",
    classification: "official",
    purpose: "Emergency PVC Conduit pipes purchased from local market",
    description: "Purchased 10 bundling conduits for line 2 junction box.",
    receiptPhoto: "https://images.unsplash.com/photo-1554224155-8d04cb21cd6c?w=300&auto=format&fit=crop&q=80",
    status: "pending", // Waiting for Superadmin approval
  },
  {
    id: "ea-403",
    employeeId: "emp-103",
    projectId: "proj-102",
    amount: 2000,
    date: "2026-08-05",
    type: "advance",
    classification: "personal",
    purpose: "Festival home travel cash advance",
    description: "Handed over by Contractor Javed.",
    receiptPhoto: null,
    status: "approved",
  },
  {
    id: "ea-404",
    employeeId: "emp-104",
    projectId: "proj-103",
    amount: 1200,
    date: "2026-08-17",
    type: "expense",
    classification: "official",
    purpose: "Copper pipe welding gas cylinder refill",
    description: "Official site expense for AC chiller unit pressure test.",
    receiptPhoto: "https://images.unsplash.com/photo-1554224155-8d04cb21cd6c?w=300&auto=format&fit=crop&q=80",
    status: "approved",
  },
];

export const INITIAL_TASKS = [
  {
    id: "task-501",
    title: "Lay Main Power Cables to Distribution Box 4",
    description: "Run armored 4-core cables from transformer room to DB-4 panel on platform 2.",
    assignedToType: "employee",
    assignedToId: "emp-101",
    projectId: "proj-101",
    assignedBy: "Javed Contractor",
    deadline: "2026-08-19",
    priority: "high",
    status: "in_progress",
    progressNotes: "Laid 120m out of 150m cable. Final termination pending.",
    completionPhoto: null,
    completedAt: null,
  },
  {
    id: "task-502",
    title: "Cast Concrete Pillars for Entrance Canopy",
    description: "Prepare shuttering, steel mesh, and pour M30 grade concrete mix.",
    assignedToType: "group",
    assignedToId: "grp-202",
    projectId: "proj-101",
    assignedBy: "Javed Contractor",
    deadline: "2026-08-20",
    priority: "high",
    status: "in_progress",
    progressNotes: "Shuttering complete. Pouring started at 11 AM.",
    completionPhoto: null,
    completedAt: null,
  },
  {
    id: "task-503",
    title: "Flyover Expansion Joint Welding Test",
    description: "Conduct ultrasonic weld testing on joint 14 to 18.",
    assignedToType: "employee",
    assignedToId: "emp-103",
    projectId: "proj-102",
    assignedBy: "Javed Contractor",
    deadline: "2026-08-18",
    priority: "medium",
    status: "completed",
    progressNotes: "Welding test passed without cracks.",
    completionPhoto: "https://images.unsplash.com/photo-1504307651254-35680f356dfd?w=300&auto=format&fit=crop&q=80",
    completedAt: "2026-08-18 05:30 PM",
  },
];

export const INITIAL_DAILY_REPORTS = [
  {
    id: "rep-601",
    employeeId: "emp-101",
    projectId: "proj-101",
    date: "2026-08-18",
    workCompleted: "Completed wiring in North Concourse and tested 44 LED fixtures.",
    workPending: "South Concourse emergency light battery backups.",
    problemsFaced: "Voltage fluctuation between 2 PM to 3:30 PM halted test meters.",
    materialRequired: "2 rolls of 2.5mm red copper wire & 50 cable ties.",
    siteObservations: "Dust accumulation near panel 2 needs vacuum cleaning.",
    photos: [
      "https://images.unsplash.com/photo-1581092160607-ee22621dd758?w=400&auto=format&fit=crop&q=80",
      "https://images.unsplash.com/photo-1581092335397-9583fe92d232?w=400&auto=format&fit=crop&q=80",
    ],
    taskCompletionStatus: "85% Done",
    status: "submitted",
    remarks: "Good work done despite voltage delay.",
  },
  {
    id: "rep-602",
    employeeId: "emp-104",
    projectId: "proj-103",
    date: "2026-08-18",
    workCompleted: "Insulated 40 meters of chilled water pipes on 3rd floor.",
    workPending: "Floor 4 main riser connections.",
    problemsFaced: "Scaffolding ladder was occupied by painting crew till noon.",
    materialRequired: "5 cans of rubber adhesive and nitrile foam rolls.",
    siteObservations: "Painting team left wet paint splatters on copper pipes.",
    photos: [
      "https://images.unsplash.com/photo-1621905251189-08b45d6a269e?w=400&auto=format&fit=crop&q=80",
    ],
    taskCompletionStatus: "100% Done",
    status: "submitted",
    remarks: "Approved. Spoke with painter lead.",
  },
];

export const INITIAL_NOTIFICATIONS = [
  {
    id: "notif-701",
    title: "Overtime Approval Required",
    message: "Rajesh Kumar (EMP-1024) has been working past 6:30 PM today (Overtime Period 1). Approval pending.",
    type: "overtime_alert",
    employeeId: "emp-101",
    date: "2026-08-19 06:35 PM",
    isRead: false,
  },
  {
    id: "notif-702",
    title: "Expense Voucher Submitted",
    message: "Sunil Verma submitted an official expense voucher of ₹850 for PVC conduits.",
    type: "expense_voucher",
    employeeId: "emp-102",
    date: "2026-08-19 04:15 PM",
    isRead: false,
  },
  {
    id: "notif-703",
    title: "Late Punch-In Alert",
    message: "Amit Sharma (EMP-5632) punched in at 10:25 AM (25 minutes past standard 10:00 AM schedule).",
    type: "late_punch",
    employeeId: "emp-103",
    date: "2026-08-19 10:25 AM",
    isRead: false,
  },
  {
    id: "notif-704",
    title: "Daily Work Completion Report Submitted",
    message: "Rajesh Kumar submitted daily work report for Metro Station Terminal A.",
    type: "daily_report_submitted",
    employeeId: "emp-101",
    date: "2026-08-18 09:20 PM",
    isRead: true,
  },
];
